version: "3"
services:
  alert-hook:
    image: rashadansari/alert-hook:1.0.1
    hostname: alert-hook
    container_name: alert-hook
    environment:
      - HTTP_ENDPOINT_HOST=alert-hook
      - HTTP_ENDPOINT_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./conf:/opt/docker/conf
